// Generates src/styles/colors.css from src/theme/themes.json (the single source of truth for built-in
// colour themes — the TS registry reads the same file), then copies src/styles into dist/styles so the
// raw, un-compiled CSS ships with the package: `@import 'perkslab-ui/styles.css'` inside the consumer's
// own Tailwind v4 build.
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const themes = JSON.parse(readFileSync(join(root, 'src/theme/themes.json'), 'utf8'));

const VAR_MAP = {
	brand: '--brand-color',
	brandHover: '--brand-hover',
	brandBg: '--brand-bg',
	brandFg: '--brand-fg',
	background: '--bg-page',
	foreground: '--text-main',
	panel: '--bg-panel',
	border: '--panel-border',
	muted: '--text-muted',
	danger: '--c-danger',
	ok: '--c-ok',
	warning: '--c-warning',
	info: '--c-info',
};

const block = (selector, decls) => `${selector} {\n${decls.map((d) => `\t${d}`).join('\n')}\n}\n`;

const themeBlock = (theme) =>
	block(
		`[data-theme='${theme.id}']`,
		[
			...Object.entries(theme.colors).map(([key, value]) => `${VAR_MAP[key]}: ${value};`),
			`color-scheme: ${theme.mode};`,
		],
	);

const css = `/* GENERATED by scripts/build-css.mjs from src/theme/themes.json — edit the JSON, not this file. */

/* Defaults every theme inherits. Anything a theme does not set explicitly is derived from its core
   colours, so a theme only has to define brand / background / foreground to look right. Declared on
   \`[data-theme]\` as well as :root so a theme applied to a nested element resolves against its own values. */
:root,
[data-theme] {
	--brand-fg: var(--bg-page);
	--bg-panel: color-mix(in srgb, var(--bg-page) 95%, var(--text-main));
	--panel-border: color-mix(in srgb, var(--bg-page) 82%, var(--text-main));
	--text-muted: color-mix(in srgb, var(--text-main) 68%, var(--bg-page));

	--c-danger: #dc2626;
	--c-ok: #15803d;
	--c-warning: #b45309;
	--c-info: #2563eb;
}

/* Dark surfaces need lighter status colours to keep their contrast. */
[data-theme='dark'],
[data-theme$='-dark'] {
	--c-danger: #f87171;
	--c-ok: #4ade80;
	--c-warning: #fbbf24;
	--c-info: #60a5fa;
}

/* The default (no data-theme) palette equals the 'light' theme. */
:root {
${Object.entries(themes.find((t) => t.id === 'light').colors)
	.map(([k, v]) => `\t${VAR_MAP[k]}: ${v};`)
	.join('\n')}
	color-scheme: light;
}

${themes.map(themeBlock).join('\n')}
body {
	background-color: var(--bg-page);
	color: var(--text-main);
}
`;

writeFileSync(join(root, 'src/styles/colors.css'), css);

rmSync(join(root, 'dist/styles'), { recursive: true, force: true });
mkdirSync(join(root, 'dist'), { recursive: true });
cpSync(join(root, 'src/styles'), join(root, 'dist/styles'), { recursive: true });
console.log(`colors.css: ${themes.length} themes; copied styles -> dist/styles`);
